### ISSUE TITLE
How about the performance of Slim-LLM on 4-bit model?

### ISSUE THREAD

**Issue by ZorkJ** [Aaronhuang-778/SliM-LLM#2]
Your paper only show the result of Slim-LLM on 3-bit and 2-bit Llama models. Have you ever tried the performance on 4-bit model?

**Comment by Aaronhuang-778** [comment]
Hi, thanks for your attention on SliM-LLM. 

In this work, we mainly focus on the low-bit (2/3-bit) context of PTQ for its huge loss in accuracy. This is because that we noticed the 4-bit quantization under advanced PTQ methods like GPTQ,AWQ and OmniQuant, etc., show great performance which is closed to FP16 models, the improving space left is limited. But there is a need to improve the PTQ performance under lower bit-width, which motivated us to propose SliM-LLM.

And we also tried it on some 4-bit models, we are happy to share the results to you:

<!DOCTYPE html><figure class="md-table-fig table-figure" cid="n2" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(0, 122, 255); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;">
Method | LLaMA-7B | LLaMA-13B | LLaMA2-7B | LLaMA2-13B | LLaMA3-8B
-- | -- | -- | -- | -- | --
FP16 | 5.68 | 5.09 | 5.47 | 4.88 | 5.75
AWQ | 5.81 | 5.30 | 5.62 | 4.97 | 6.63
GPTQ | 5.85 | 5.20 | 5.61 | 4.98 | 6.50
SliM-LLM | 5.83 | 5.16 | 5.59 | 4.95 | 6.42

<!DOCTYPE html><figure class="md-table-fig table-figure" cid="n106" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(0, 122, 255); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;">
Method | LLaMA-7B | LLaMA2-7B
-- | -- | --
Omniquant | 5.77 | 5.58
SliM-LLM+ | 5.75 | 5.57

Tables show the leading performance of SliM-LLM and SliM-LLM+ , for its considering of mixed-precision and can be used as a plug-and-play method into GPTQ and OmniQuant. As mentioned before, the left improving space is limited between 4-bit and 16-bit, so we could not get the same relative performance improving as 2/3-bit. But we could still see the power of SliM-LLM. Hope this reply is helpful to you!

**Comment by ZorkJ** [comment]
Thanks very much for your detalied reply. It's very informative. Another question is that whether the performance of 3-bit SliM-LLM+ llama3 70B can be comparable to 4-bit GPTQ or GGUF llama3 70b model. In another way, do you think whether its worthy to use 3-bit SliM-LLM+ llama3 70B as an alternative to 4-bit GPTQ or GGUF llama3 70b model to pursue low memory cost without much performance sacrifice?

**Comment by Aaronhuang-778** [comment]
This is a good question. From our work, we find SliM-LLM+ could reach the closest performance to 4-bit PTQ method at 3-bit with only slight loss, in a inference friendly way. 

As to llama-3 model, you can refer this work "How Good Are Low-bit Quantized LLAMA3 Models? An Empirical Study[1]". We find llama-3 models are more sensitive to quantization, which means they will suffer more accuracy loss when the bit-width changing from 4-bit to 3-bit. We can see that the 3-bit performance of llama-65B and llama-2-70B are better than llama-3-70B with current advanced quantization methods. So the performance recovering under 3-bit llama-3 models is more challenging than llama and llama-2.

And the bit-width choosing really depends on your hardware limitation and LLMs performance trade-off. 3-bit models are better for edged and resource-limited platforms with smaller model size and slight accuracy drop, 4-bit models are suitable for the high-accuracy needed scenario but with larger memory. Both of 3-bit and 4-bit models are already applied in industrial use, which show 3-bit or lower-bit models also have great potential capability for application. We hope to continue pushing it with our community. :smile:


[1]https://arxiv.org/pdf/2404.14047

**Comment by ZorkJ** [comment]
I found that in your Slim-LLM paper, Llama3-8B 16-bit model perform worse than Llama1-7B 16-bit model and Llama2-7B 16-bit model. Llama3-70B 16-bit model perform worse than Llama1-65B 16-bit model and Llama2-70B 16-bit model both on WikiText2 and C4 dataset. Do you think this result is reasonable?

**Comment by Aaronhuang-778** [comment]
Yes, I think these benchmark results are acceptable. In SliM-LLM, we control all the experiments in the same hardware and CONDA environment. Here, we set all the test token lengths as 2k for the alignment with previous works and it is suitable for OPT, LLaMA1/2, and LLaMA3. But the biggest advantage of LLaMA3 is 8k context understanding, where LLaMA3-8B shows better results than others with 2k or 4k context (LLaMA1/2's max context length is only 4k).

Under 2k experiments set up, we can find LLaMA3-8B shows worse PPL on WikiText2 and C4 datasets, LLaMA3-70B shows worse PPL on C4 but better on WikiText2 (these results are aligned with [1]). However, PPL only reflects the token prediction capability of LLMs which is usually used to measure the accuracy loss under the quantization context, but not the general ability of LLMs, we can not judge the capability with only the PPL metric. 

You can also find the CommonSenseQA (some zero-shot benchmarks) results in [1], which are more general capability test datasets. We can see LLaMA3 model shows better performance than LLaMA/2. To compare the quantization method in a more comprehensive approach,  in SliM-LLM,  we also compared this general metric of LLMs' capability on different PTQ methods to show the performance advantages of our proposed method (but not for revealing the difference between LLaMA1/2 and LLaMA3).

**Comment by ZorkJ** [comment]
Many thanks for your thorough comments. I learn a lot from your answer. Hope your SliM-LLM will have great success.
