### ISSUE TITLE
Clarification on Theorem 1 of the Paper

### ISSUE THREAD

**Issue by kiucho** [Aaronhuang-778/SliM-LLM#6]
Thanks for sharing great research. I have a question regarding Theorem 1, and I would appreciate your clarification.

In Theorem 1, it is mentioned: "...which further leads to the parameter salience being larger at the p-th channel of weight...".

From my understanding, the outlier value $x_{p,q}$ in the activation matrix $x$ causes the diagonal element of $xx^\top$ at position $p, p$ to become an outlier. This suggests that token $p$ is particularly salient across the channels.

However, considering that the outlier occurs at channel $q$ for token $p$, wouldn't it imply that the salience is larger at the **q-th channel** of the weight matrix, rather than the p-th channel? Could you please clarify this?

Thank you in advance for your time and response.

**Comment by Aaronhuang-778** [comment]
Hi @kiucho, you are right. In fact, the outlier channel (q) in the activation rather than the value of token (p) primarily influences the Hessian approximation. This ultimately leads to the trace of the Hessian being more anomalous at position q, thereby affecting the weight salience of the q-th channel. We have corrected this error in the new version of the paper. Due to other reasons, the updated version has not been uploaded to arXiv. Your reminder has prompted us to swiftly rectify this typo. Thank you for your attention to detail in the research, and best of luck with your upcoming work!

**Comment by kiucho** [comment]
Given this clarification, can I then understand that the salience of the weight channel is determined by $x^\top x$ instead of $xx^\top$?

**Comment by Aaronhuang-778** [comment]
> Given this clarification, can I then understand that the salience of the weight channel is determined by x ⊤ x instead of x x ⊤ ?

Yes, your comment is right. We finally utilized $x^\top x$ as the description of Hessian. Here is the revised version of Theorem 1. Hope it will help you.


![WX20241015-150315](https://github.com/user-attachments/assets/b1828e91-70ea-4358-882c-1b2e24fb93a9)

**Comment by kiucho** [comment]
Thank you so much for clarification!
